import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { buildPrompt, cleanAiOutput, REPORT_TYPES, type ReportType } from "@/lib/report";
import { resolveApiKey } from "@/lib/openai-key";

export const runtime = "nodejs";

// ── Payload size limits — Fix C2 (token amplification) ──────────────────────
const MAX_SUMMARY_CHARS = 8_000;
const MAX_FIELD_CHARS   = 300;

// ── Free-tier limits ─────────────────────────────────────────────────────────
const FREE_LIMIT     = 3;                      // max generate sessions per browser
const COOKIE_NAME    = "nixara_ftu";           // HttpOnly — JS cannot read/modify
const COOKIE_MAX_AGE = 60 * 60 * 24 * 30;     // 30 days

/**
 * Cookie-based free-tier gate.
 *
 * The cookie stores a JSON array of session UUIDs — one UUID is generated by
 * the client per "Generate Report" button click and sent with every report-type
 * call in that session.  This means the gate counts full generate SESSIONS
 * (not individual API calls), regardless of how many report types exist.
 *
 * Why cookies instead of IP/KV:
 *   - Vercel serverless functions are stateless across cold starts — an
 *     in-memory Map resets on every cold start and is not shared between
 *     concurrent instances, so IP-based in-memory counting is non-functional
 *     in production.
 *   - An HttpOnly server-set cookie persists for 30 days and survives tab
 *     closes, browser restarts, and system reboots, making it significantly
 *     harder to bypass than sessionStorage.
 *   - No external service (KV, Redis) required.
 */
function checkFreeTierCookie(
  req: NextRequest,
  sessionId: string | undefined
): { allowed: boolean; sessions: string[]; isNewSession: boolean } {
  const raw = req.cookies.get(COOKIE_NAME)?.value ?? "[]";
  let sessions: string[] = [];
  try {
    const parsed = JSON.parse(raw);
    sessions = Array.isArray(parsed) ? parsed.filter((s) => typeof s === "string") : [];
  } catch {
    sessions = [];
  }

  // Same session already started (different report type call) — always allow.
  if (sessionId && sessions.includes(sessionId)) {
    return { allowed: true, sessions, isNewSession: false };
  }

  // New session — check whether the limit has been reached.
  const isNewSession = !!sessionId;
  if (isNewSession && sessions.length >= FREE_LIMIT) {
    return { allowed: false, sessions, isNewSession: true };
  }

  return { allowed: true, sessions, isNewSession };
}

interface Body {
  who: string;
  decision: string;
  timeframe: string;
  reportType: ReportType;
  summary: string;
  userKey?: string;
  /** UUID generated once per "Generate Report" click, shared across all report-type calls. */
  sessionId?: string;
}

export async function POST(req: NextRequest) {
  let body: Body;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 });
  }

  const { who, decision, timeframe, reportType, summary, userKey, sessionId } = body;

  // ── Required field check ─────────────────────────────────────────────────
  if (!who || !decision || !timeframe || !summary) {
    return NextResponse.json({ error: "Missing required fields." }, { status: 400 });
  }
  if (!REPORT_TYPES.includes(reportType)) {
    return NextResponse.json({ error: "Invalid report type." }, { status: 400 });
  }

  // ── Payload size caps (Fix C2) ───────────────────────────────────────────
  if (summary.length > MAX_SUMMARY_CHARS) {
    return NextResponse.json(
      { error: `Summary too large — maximum ${MAX_SUMMARY_CHARS.toLocaleString()} characters allowed.` },
      { status: 413 }
    );
  }
  if (
    who.length       > MAX_FIELD_CHARS ||
    decision.length  > MAX_FIELD_CHARS ||
    timeframe.length > MAX_FIELD_CHARS
  ) {
    return NextResponse.json(
      { error: "One or more fields exceed the maximum allowed length." },
      { status: 413 }
    );
  }

  // ── Resolve API key & tier ───────────────────────────────────────────────
  const { apiKey, tier } = resolveApiKey(userKey);
  if (!apiKey) {
    return NextResponse.json(
      { error: "No OpenAI API key available. Paste your own key, or contact the admin." },
      { status: 401 }
    );
  }

  // ── Server-side free-tier gate (cookie-based, survives restarts) ──────────
  if (tier === "free") {
    const { allowed, sessions, isNewSession } = checkFreeTierCookie(req, sessionId);

    if (!allowed) {
      return NextResponse.json(
        {
          error:
            `You've used all ${FREE_LIMIT} free generate sessions. ` +
            "Paste your own OpenAI key (starts with sk-) in the field below to continue.",
        },
        { status: 429 }
      );
    }

    const prompt = buildPrompt({ who, decision, timeframe, reportType, summary });
    try {
      const client   = new OpenAI({ apiKey });
      const response = await client.chat.completions.create({
        model:      "gpt-4o",
        max_tokens: 1024,
        messages:   [{ role: "user", content: prompt }],
      });
      const raw  = response.choices[0]?.message?.content ?? "";
      const text = cleanAiOutput(raw);

      // Only record a new session on success — failed generations don't count.
      const updatedSessions = isNewSession && sessionId
        ? [...sessions, sessionId]
        : sessions;
      const freeRemaining = Math.max(0, FREE_LIMIT - updatedSessions.length);

      const res = NextResponse.json({ text, tier, freeRemaining });
      res.cookies.set(COOKIE_NAME, JSON.stringify(updatedSessions), {
        httpOnly: true,                                      // JS cannot read this
        secure:   process.env.NODE_ENV === "production",    // HTTPS only in prod
        sameSite: "lax",
        maxAge:   COOKIE_MAX_AGE,                           // 30 days
        path:     "/",
      });
      return res;
    } catch (err) {
      return NextResponse.json({ error: safeOpenAiErrorMessage(err) }, { status: 502 });
    }
  }

  // ── Own key / admin tier — no free-tier gate ─────────────────────────────
  const prompt = buildPrompt({ who, decision, timeframe, reportType, summary });
  try {
    const client   = new OpenAI({ apiKey });
    const response = await client.chat.completions.create({
      model:      "gpt-4o",
      max_tokens: 1024,
      messages:   [{ role: "user", content: prompt }],
    });
    const raw  = response.choices[0]?.message?.content ?? "";
    const text = cleanAiOutput(raw);
    return NextResponse.json({ text, tier });
  } catch (err) {
    return NextResponse.json({ error: safeOpenAiErrorMessage(err) }, { status: 502 });
  }
}

/**
 * SECURITY FIX (2026-08): info disclosure via error passthrough.
 *
 * This used to return `err.message` from the OpenAI SDK straight to the
 * browser. Depending on the failure, that string can include billing/quota
 * details, org identifiers, or other account-specific text tied to
 * whichever key served the request (Nixara's own key on the free tier, or
 * the caller's own pasted key) — none of which should end up in a client
 * network tab. We classify into a few safe, generic buckets instead. Full
 * detail still isn't logged anywhere server-side today (no logger is wired
 * up) — that's a separate follow-up, not something this function can fix.
 */
function safeOpenAiErrorMessage(err: unknown): string {
  const status =
    err && typeof err === "object" && "status" in err ? (err as { status?: number }).status : undefined;

  if (status === 401) return "The OpenAI key on file was rejected. Check the key and try again.";
  if (status === 429) return "OpenAI rate or quota limit reached. Wait a moment and try again.";
  if (status && status >= 500) return "OpenAI is temporarily unavailable. Please try again shortly.";
  return "Report generation failed. Please try again.";
}
